name: 'sqedw_dbt'
version: '1.0.0'

profile: 'sqedw_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  sqedw_dbt:
    staging:
      +schema: staging
      +materialized: view

seeds:
  sqedw_dbt:
    codemaster:
      +schema: staging
      +quote_columns: false